// SPDX-FileCopyrightText: 2026 Sebastien Rousseau
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Embed the rule set at compile time.
//!
//! A WASM build has no filesystem, so `rules/*.toml` cannot be read at
//! runtime. They are baked in here instead, from the same `agtmls-spec`
//! checkout the conformance suite uses — so the embedded rules are the
//! specification's rules, not a copy that can drift.
//!
//! This fails the build when the spec is absent rather than embedding an
//! empty set. A WASM module that reports zero findings because it has no
//! rules is indistinguishable, to its caller, from one that found nothing.

use std::path::{Path, PathBuf};

fn spec_dir() -> Option<PathBuf> {
    if let Ok(dir) = std::env::var("AGTMLS_SPEC") {
        let path = PathBuf::from(dir);
        if path.join("rules").is_dir() {
            return Some(path);
        }
    }
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").ok()?);
    ["../agtmls-spec", "../../Other/agtmls-spec"]
        .into_iter()
        .map(|candidate| manifest.join(candidate))
        .find(|path| path.join("rules").is_dir())
}

/// Minimum `#` count for a raw string literal holding `body`.
///
/// A raw string `r#*"…"#*` terminates at the first `"` followed by that many
/// `#`. So: none needed if the body has no quote at all, otherwise one more
/// than the longest run of `#` immediately following a quote.
fn raw_hashes_needed(body: &str) -> usize {
    if !body.contains('"') {
        return 0;
    }
    let bytes = body.as_bytes();
    let mut longest = 0;
    for (index, byte) in bytes.iter().enumerate() {
        if *byte != b'"' {
            continue;
        }
        let run = bytes[index + 1..]
            .iter()
            .take_while(|b| **b == b'#')
            .count();
        longest = longest.max(run);
    }
    longest + 1
}

fn main() {
    println!("cargo:rerun-if-env-changed=AGTMLS_SPEC");

    let Some(spec) = spec_dir() else {
        panic!(
            "agtmls-spec not found. Set AGTMLS_SPEC to a checkout of \
             https://github.com/sebastienrousseau/agtmls-spec. Refusing to embed an \
             empty rule set: a module that finds nothing because it has no rules looks \
             exactly like one that found nothing."
        );
    };
    let rules_dir = spec.join("rules");
    println!("cargo:rerun-if-changed={}", rules_dir.display());

    let mut entries: Vec<_> = std::fs::read_dir(&rules_dir)
        .expect("read rules dir")
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "toml"))
        .collect();
    entries.sort();
    assert!(
        !entries.is_empty(),
        "no rules found in {}",
        rules_dir.display()
    );

    let mut generated = String::from(
        "// @generated by build.rs from agtmls-spec/rules. Do not edit.\n\
         /// Rule sources embedded at compile time from `agtmls-spec/rules`.\n\
         pub const EMBEDDED_RULES: &[(&str, &str)] = &[\n",
    );
    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        let body = std::fs::read_to_string(path).expect("read rule");
        // Exactly as many hashes as the body requires, no more: a fixed count
        // large enough for any input is always wrong for most of them, and
        // clippy is right to say so.
        let hashes = "#".repeat(raw_hashes_needed(&body));
        generated.push_str(&format!("    ({name:?}, r{hashes}\"{body}\"{hashes}),\n"));
    }
    generated.push_str("];\n");

    let out = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_rules.rs");
    std::fs::write(&out, generated).expect("write embedded rules");
    println!(
        "cargo:warning=embedded {} rule(s) from {}",
        entries.len(),
        rules_dir.display()
    );
}
